import{S as l,i as c}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const d="48303483-31cfd41ec7662904a2a6a727b",u="https://pixabay.com/api/";async function m(a,r=1,o=12){const i=`${u}?key=${d}&q=${encodeURIComponent(a)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${o}`,e=await fetch(i);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}function f({webformatURL:a,largeImageURL:r,tags:o,likes:i,views:e,comments:t,downloads:s}){return`
  <a href="${r}" class="gallery-item" data-title="${o}">
    <img src="${a}" alt="${o}" loading="lazy" />
    <div class="info">
      <p class="info-item"><b>Likes</b>${i}</p>
      <p class="info-item"><b>Views</b>${e}</p>
      <p class="info-item"><b>Comments</b>${t}</p>
      <p class="info-item"><b>Downloads</b>${s}</p>
    </div>
  </a>
`}function p(a){const r=document.querySelector(".gallery");r.innerHTML=a.map(f).join(""),new l(".gallery a",{captions:!0,captionsData:"title",captionDelay:250}).refresh()}const h=document.querySelector("#search-form"),y=document.querySelector(".gallery"),n=document.createElement("div");n.classList.add("loader","hidden");document.body.appendChild(n);h.addEventListener("submit",async a=>{a.preventDefault();const r=a.currentTarget.elements.searchQuery.value.trim();if(!r){c.error({title:"Error",message:"Please enter a search query"});return}try{n.classList.remove("hidden"),y.innerHTML="";const o=await m(r);setTimeout(()=>{if(n.classList.add("hidden"),o.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}p(o.hits),new SimpleLightbox(".gallery a",{captions:!0,captionsData:"title",captionDelay:250}).refresh()},1e3)}catch(o){c.error({title:"Error",message:o.message}),n.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
