import{S as l,i as c}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const d="48303483-31cfd41ec7662904a2a6a727b",u="https://pixabay.com/api/";async function m(i,r=1,o=12){const s=`${u}?key=${d}&q=${encodeURIComponent(i)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${o}`,e=await fetch(s);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}function f({webformatURL:i,largeImageURL:r,tags:o,likes:s,views:e,comments:t,downloads:a}){return`
    <a href="${r}" class="gallery-item" title="${o}">
      <img src="${i}" alt="${o}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes</b>${s}</p>
        <p class="info-item"><b>Views</b>${e}</p>
        <p class="info-item"><b>Comments</b>${t}</p>
        <p class="info-item"><b>Downloads</b>${a}</p>
      </div>
    </a>
  `}function p(i){const r=document.querySelector(".gallery");r.innerHTML=i.map(f).join("")}function h(){new l(".gallery a",{captions:!0,captionsData:"title",captionDelay:250}).refresh()}const y=document.querySelector("#search-form"),g=document.querySelector(".gallery"),n=document.createElement("div");n.classList.add("loader","hidden");document.body.appendChild(n);y.addEventListener("submit",async i=>{i.preventDefault();const r=i.currentTarget.elements.searchQuery.value.trim();if(!r){c.error({title:"Error",message:"Please enter a search query"});return}try{n.classList.remove("hidden"),g.innerHTML="";const o=await m(r);setTimeout(()=>{if(n.classList.add("hidden"),o.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}p(o.hits),h()},1e3)}catch(o){c.error({title:"Error",message:o.message}),n.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
